/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gpa.calculator;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JViewport;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import javax.swing.border.EmptyBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Kunal Prasad
 */
public class GPA_Calculator_GUI extends javax.swing.JFrame {

    /**
     * Creates new form GPA_Calculator_GUI
     */

    public GPA_Calculator_GUI() {
        initComponents();
        recreate();
        External_Elements();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_white_background = new javax.swing.JScrollPane();
        jPanel_white_background = new javax.swing.JPanel();
        jLabel_header_text_1 = new javax.swing.JLabel();
        jLabel_header_text_2 = new javax.swing.JLabel();
        jLabel_version = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane_white_background.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane_white_background.setBorder(null);
        jScrollPane_white_background.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane_white_background.setAlignmentX(0.0F);
        jScrollPane_white_background.setAlignmentY(0.0F);

        jPanel_white_background.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_white_background.setAutoscrolls(true);
        jPanel_white_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_header_text_1.setFont(new java.awt.Font("Google Sans", 1, 48)); // NOI18N
        jLabel_header_text_1.setForeground(new java.awt.Color(62, 100, 255));
        jLabel_header_text_1.setText("GPA");
        jPanel_white_background.add(jLabel_header_text_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 40));

        jLabel_header_text_2.setFont(new java.awt.Font("Google Sans Medium", 0, 36)); // NOI18N
        jLabel_header_text_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_header_text_2.setText("Calculator");
        jPanel_white_background.add(jLabel_header_text_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel_version.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        jLabel_version.setText("v1.0");
        jPanel_white_background.add(jLabel_version, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jScrollPane_white_background.setViewportView(jPanel_white_background);

        getContentPane().add(jScrollPane_white_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 880, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
     ArrayList <JScrollPane> sp_semester_panel_scrollpane = new ArrayList <JScrollPane> ();
     ArrayList <JPanel> panel_semester_panel = new ArrayList <JPanel> ();
     ArrayList <JLabel> label_semester_panel_title = new ArrayList <JLabel> ();
     ArrayList <JLabel> label_course_name = new ArrayList <JLabel> ();
     ArrayList <JLabel> label_grade = new ArrayList <JLabel> ();
     ArrayList <JLabel> label_credit = new ArrayList <JLabel> ();
     ArrayList <JLabel> label_result = new ArrayList <JLabel> ();
     ArrayList <JTextField> tf_course_name = new ArrayList <JTextField> ();
     ArrayList <JTextField> tf_grade = new ArrayList <JTextField> ();
     ArrayList <JTextField> tf_credit = new ArrayList <JTextField> ();
     ArrayList <JButton> button_add_course = new ArrayList <JButton> ();
     ArrayList <JButton> button_remove_course = new ArrayList <JButton> ();
     ArrayList <JButton> button_add_semester = new ArrayList <JButton> ();
     ArrayList <JButton> button_calculate_gpa = new ArrayList <JButton> ();
     int semester_counter = -1;
     int textfield_counter = -1;
     int positionY_prevoius_coursename_textfield = 0;
     int initial_number_of_textfields = 4;
     boolean initial_flag = true;
     private void recreate ()
     {
                 //Add_Image();
        JScrollPane scroll = new JScrollPane();
        scroll.setBorder(new EmptyBorder(0, 0, 0, 0));
        
        JPanel panel = new JPanel ();
        panel.setBackground(new Color(236, 252, 255, 170));
        //panel.setBackground(new Color(62, 100, 255, 50));
        panel.setLayout(new AbsoluteLayout());
        
        JLabel head_title = new JLabel();
        head_title.setFont(new Font ("Google Sans Medium", 0, 18));
        head_title.setText("Semester " + (semester_counter + 2));
        
        JLabel result = new JLabel();
        result.setForeground(new java.awt.Color(62, 100, 255));
        result.setFont(new Font ("Google Sans Medium", 1, 36));
        result.setText("1.00");
        
        JLabel gpa = new JLabel();
        gpa.setFont(new Font ("Google Sans", 0, 18));
        gpa.setText("GPA");
        
        JLabel courses = new JLabel();
        courses.setFont(new Font ("Google Sans", 0, 12));
        courses.setText("Courses");
        
        JLabel table_legend_course_name = new JLabel();
        table_legend_course_name.setFont(new Font ("Google Sans", 0, 10));
        table_legend_course_name.setText("Course Name");
        
        JLabel table_legend_grade = new JLabel();
        table_legend_grade.setFont(new Font ("Google Sans", 0, 10));
        table_legend_grade.setText("Grade");
        
        JLabel table_legend_credit = new JLabel();
        table_legend_credit.setFont(new Font ("Google Sans", 0, 10));
        table_legend_credit.setText("Credit");     
        
        JButton add_course = new JButton();
        add_course.setFont(new Font("Google Sans Medium", 0, 12));
        add_course.setBackground(Color.white);
        add_course.setText("+");
        add_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Courses (panel);
            }
        });
        
        JButton remove_course = new JButton();
        remove_course.setFont(new Font("Google Sans Medium", 0, 12));
        remove_course.setBackground(Color.white);
        remove_course.setText("-");
        remove_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_Courses (panel);
            }
        });
        
        JButton calculate_gpa = new JButton();
        calculate_gpa.setFont(new Font("Google Sans Medium", 0, 14));
        calculate_gpa.setForeground(Color.white);
        calculate_gpa.setBackground(new Color(62, 100, 255, 150));
        calculate_gpa.setText("Calculate");
        calculate_gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //Eliminate_Blank_Textfield(panel);
                Calculate_Grade();
                Calculate_Credit();
                Post_GPA();
            }
        });
        
        JButton clear = new JButton();
        clear.setFont(new Font("Google Sans", 1, 10));
        clear.setBackground(Color.white);
        clear.setText("AC");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear(panel);
            }
        });
        
        if( initial_flag )
        {
           for(int i = 0; i < initial_number_of_textfields; i++)
           {
               positionY_prevoius_coursename_textfield = (30*i);
               
               JTextField course_name = new JTextField();
               JTextField grade = new JTextField();
               JTextField credit = new JTextField();
               
               course_name.setFont(new java.awt.Font("Google Sans", 0, 12));
               grade.setFont(new java.awt.Font("Google Sans", 0, 12));
               credit.setFont(new java.awt.Font("Google Sans", 0, 12));
               
               course_name.setBorder(new EmptyBorder(0, 0, 0, 0));
               grade.setBorder(new EmptyBorder(0, 0, 0, 0));
               credit.setBorder(new EmptyBorder(0, 0, 0, 0));
               
               panel.add(course_name, new AbsoluteConstraints (10, 50 + (positionY_prevoius_coursename_textfield), 210, 30));
               panel.add(grade, new AbsoluteConstraints (220, 50 + (positionY_prevoius_coursename_textfield), 70, 30));
               panel.add(credit, new AbsoluteConstraints (290, 50 + (positionY_prevoius_coursename_textfield), 80, 30));         
               
               tf_course_name.add(course_name);
               tf_grade.add(grade);
               tf_credit.add(credit);
               
               ++textfield_counter;
               //System.out.println("Y :"+ positionY_prevoius_coursename_textfield);
               
               revalidate();
               repaint();
           }              
        }
        
        /*
        panel.add(head_title, new AbsoluteConstraints (10, 10, -1, -1));
        panel.add(result, new AbsoluteConstraints (480, 40, -1, -1));
        panel.add(gpa, new AbsoluteConstraints (520, 80, -1, -1));
        panel.add(add_course, new AbsoluteConstraints (530, 130, -1, -1));
        panel.add(remove_course, new AbsoluteConstraints (445, 130, -1, -1));
        panel.add(courses, new AbsoluteConstraints ( 480, 137, -1, -1));
        panel.add(table_legend_course_name, new AbsoluteConstraints ( 10, 40, -1, -1));
        panel.add(table_legend_grade, new AbsoluteConstraints ( 220, 40, -1, -1));
        panel.add(table_legend_credit, new AbsoluteConstraints ( 290, 40, -1, -1));
        panel.add(calculate_gpa, new AbsoluteConstraints ( 445, 165, 120, 35));
        panel.add(clear, new AbsoluteConstraints ( 400, 130, -1, 70));
        */
        panel.add(head_title, new AbsoluteConstraints (10, 10, -1, -1));
        panel.add(result, new AbsoluteConstraints (480, 40, -1, -1));
        panel.add(gpa, new AbsoluteConstraints (520, 80, -1, -1));
        panel.add(add_course, new AbsoluteConstraints (480, 135, -1, -1));
        panel.add(remove_course, new AbsoluteConstraints (395, 135, -1, -1));
        panel.add(courses, new AbsoluteConstraints ( 430, 142, -1, -1));
        panel.add(table_legend_course_name, new AbsoluteConstraints ( 10, 40, -1, -1));
        panel.add(table_legend_grade, new AbsoluteConstraints ( 220, 40, -1, -1));
        panel.add(table_legend_credit, new AbsoluteConstraints ( 290, 40, -1, -1));
        panel.add(calculate_gpa, new AbsoluteConstraints ( 395, 165, 120, 35));
        panel.add(clear, new AbsoluteConstraints ( 520, 135, -1, 65));
                   
        scroll.setViewportView ( panel );
        scroll.getViewport().setScrollMode(JViewport.SIMPLE_SCROLL_MODE);
        
        //getContentPane().add( scroll,new AbsoluteConstraints (30, 120, 580, 220));
        //jPanel1.add(scroll,new AbsoluteConstraints (30, 120, 580, 220));
        //getContentPane().add( panel,new AbsoluteConstraints (30, 120, 580, 220));
        jPanel_white_background.add(scroll, new AbsoluteConstraints (30, 120, 580, 220));
        //jPanel1.add(scroll);
        
        
        sp_semester_panel_scrollpane.add(scroll);
        panel_semester_panel.add(panel);
        label_semester_panel_title.add(head_title);
        label_result.add(result);
        button_add_course.add(add_course);
        button_remove_course.add(remove_course);
        
        ++semester_counter;
        
        if(initial_flag)
        {
            jScrollPane_white_background.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
            
            result.setText("-");
            
            initial_flag = false;
        }
        
        panel.setVisible(true);
        scroll.setVisible(true);
        pack();
        revalidate();
        repaint();
     }
     private void Add_Courses (JPanel panel)
     {
        JTextField course_name = new JTextField();
        JTextField grade = new JTextField();
        JTextField credit = new JTextField();
               
        course_name.setFont(new java.awt.Font("Google Sans", 0, 12));
        grade.setFont(new java.awt.Font("Google Sans", 0, 12));
        credit.setFont(new java.awt.Font("Google Sans", 0, 12));
               
        course_name.setBorder(new EmptyBorder(0, 0, 0, 0));
        grade.setBorder(new EmptyBorder(0, 0, 0, 0));
        credit.setBorder(new EmptyBorder(0, 0, 0, 0));
        
        positionY_prevoius_coursename_textfield = positionY_prevoius_coursename_textfield + 30;
               
        panel.add(course_name, new AbsoluteConstraints (10, 50 + (positionY_prevoius_coursename_textfield), 210, 30));
        panel.add(grade, new AbsoluteConstraints (220, 50 + (positionY_prevoius_coursename_textfield), 70, 30));
        panel.add(credit, new AbsoluteConstraints (290, 50 + (positionY_prevoius_coursename_textfield), 80, 30));         
               
               tf_course_name.add(course_name);
               tf_grade.add(grade);
               tf_credit.add(credit);
               
               ++textfield_counter;
               //System.out.println("Y :"+ positionY_prevoius_coursename_textfield);
               
               revalidate();
               repaint();
     }
     private void Remove_Courses (JPanel panel)
     {
         if(tf_course_name.size() > 1)
         {
            //System.out.println("tf_course_name size :"+ tf_course_name.size());
            
            //(tf_course_name.get(tf_course_name.size() - 1)).setVisible(false);
            panel.remove((tf_course_name.get(tf_course_name.size() - 1)));
            tf_course_name.remove(tf_course_name.size() - 1);
            
            //(tf_grade.get(tf_grade.size() - 1)).setVisible(false);
            panel.remove(tf_grade.get(tf_grade.size() - 1));
            tf_grade.remove(tf_grade.size() - 1);
            
            //(tf_credit.get(tf_credit.size() - 1)).setVisible(false);
            panel.remove((tf_credit.get(tf_credit.size() - 1)));
            tf_credit.remove(tf_credit.size() - 1);
            
            positionY_prevoius_coursename_textfield = positionY_prevoius_coursename_textfield - 30;
            
            --textfield_counter;
         
            revalidate();
            repaint();
         }
     }
     private void Eliminate_Blank_Textfield(JPanel panel)
     {
         System.out.println("Eliminate_Blank_Textfield textfield_counter :"+textfield_counter);
         int leng = tf_course_name.size() - 1;
         for(int i = 0;i <= leng; i++)
         {
             System.out.println("Eliminate_Blank_Textfield i :"+i);
             if((tf_course_name.get(i).getText().equalsIgnoreCase("")) && (tf_grade.get(i).getText().equalsIgnoreCase("")) 
                     && (tf_credit.get(i).getText().equalsIgnoreCase("")))
             {
                 System.out.println("Eliminate_Blank_Textfield contion true :"+i);
                 panel.remove(tf_course_name.get(i));
                 //tf_course_name.remove(i);
                 
                 panel.remove(tf_grade.get(i));
                 //tf_grade.remove(i);
                 
                 panel.remove(tf_credit.get(i));
                 //tf_credit.remove(i);
                 
                 --textfield_counter;
             }
         }
         revalidate();
         repaint();
     }
     private void External_Elements()
     {
        JLabel kunaleverywhere = new JLabel();
        kunaleverywhere.setFont(new Font ("Google Sans Medium", 0, 12));
        kunaleverywhere.setText("© KunalEveryWhere");
        
        JButton exit = new JButton();
        exit.setFont(new Font("Google Sans Medium", 0, 12));
        exit.setBackground(Color.white);
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });
        
        JLabel jlabel_header_picture = new JLabel();
        jlabel_header_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/undraw_cloud_docs_p4ob.png"))); // NOI18N
        
        
        //jPanel_white_background.add(jlabel_header_picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 500, -1));
        jPanel_white_background.add(jlabel_header_picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 10, 500, -1));
        jPanel_white_background.add(kunaleverywhere, new AbsoluteConstraints (20, (jPanel_white_background.getHeight()) - 20, -1, -1));
        jPanel_white_background.add(exit, new AbsoluteConstraints ((jPanel_white_background.getWidth()) - 105, (jPanel_white_background.getHeight()) - 35, 100, 30));

        revalidate();
        repaint();
        
     }
     private void Clear(JPanel panel)
     {
         int size = tf_course_name.size() - 1;
         for(int i = 0; i <= size; i++)
         {
             tf_course_name.get(i).setText("");
             tf_grade.get(i).setText("");
             tf_credit.get(i).setText("");
             label_result.get(label_result.size()-1).setText("-");
         }
     }
     String grade[];
     private void Calculate_Grade ()
     {
         int size = tf_grade.size();
         grade = new String [size];
         for(int i = 0; i < size; i++)
         {
             //if((tf_grade.get(i)).getText().equalsIgnoreCase("") == false)
                grade[i] = (tf_grade.get(i)).getText();
             //else
              //   --i;
         }
     }
     int credit[];
     private void Calculate_Credit ()
     {
         int size = tf_credit.size();
         credit = new int [size];
         for(int i = 0; i < size; i++)
         {
                credit[i] = Integer.valueOf((tf_credit.get(i)).getText());
         }
     }
     void Post_GPA ()
     {
         GPA_Calculator_Back_End app = new GPA_Calculator_Back_End();
         double result = app.GPA_Calculator(grade, credit);
         (label_result.get(0)).setText(""+result);
         revalidate();
         repaint();
     }
     


    public static void main(String args[]) {   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPA_Calculator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPA_Calculator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPA_Calculator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPA_Calculator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPA_Calculator_GUI().setVisible(true);
            }
        });
        
        //    My Test Code Starts

        //    My Test Code Ends
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_header_text_1;
    private javax.swing.JLabel jLabel_header_text_2;
    private javax.swing.JLabel jLabel_version;
    private javax.swing.JPanel jPanel_white_background;
    private javax.swing.JScrollPane jScrollPane_white_background;
    // End of variables declaration//GEN-END:variables
}
