/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gpa.calculator;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.border.EmptyBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Kunal Prasad
 */
public class GUI_Test_2 extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Test_2
     */
    public GUI_Test_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 840, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    ArrayList <JScrollPane> sp_semester_panel_scrollpane = new ArrayList <JScrollPane> ();
     ArrayList <JPanel> panel_semester_panel = new ArrayList <JPanel> ();
     ArrayList <JLabel> label_semester_panel_title = new ArrayList <JLabel> ();
     ArrayList <JLabel> label_course_name = new ArrayList <JLabel> ();
     ArrayList <JLabel> label_grade = new ArrayList <JLabel> ();
     ArrayList <JLabel> label_credit = new ArrayList <JLabel> ();
     ArrayList <JLabel> label_result = new ArrayList <JLabel> ();
     ArrayList <JTextField> tf_course_name = new ArrayList <JTextField> ();
     ArrayList <JTextField> tf_grade = new ArrayList <JTextField> ();
     ArrayList <JTextField> tf_credit = new ArrayList <JTextField> ();
     ArrayList <JButton> button_add_course = new ArrayList <JButton> ();
     ArrayList <JButton> button_remove_course = new ArrayList <JButton> ();
     ArrayList <JButton> button_add_semester = new ArrayList <JButton> ();
     int semester_counter = -1;
     int textfield_counter = -1;
     int positionY_prevoius_coursename_textfield = 0;
     boolean initial_flag = true;
     private void recreate ()
     {
        JScrollPane scroll = new JScrollPane();
        scroll.setBorder(new EmptyBorder(0, 0, 0, 0));
        
        JPanel panel = new JPanel ();
        panel.setBackground(new Color(236, 252, 255, 95));
        panel.setLayout(new AbsoluteLayout());
        
        JLabel head_title = new JLabel();
        head_title.setFont(new Font ("Google Sans Medium", 0, 18));
        head_title.setText("Semester " + (semester_counter + 1));
        
        JLabel result = new JLabel();
        result.setForeground(new java.awt.Color(62, 100, 255));
        result.setFont(new Font ("Google Sans Medium", 1, 36));
        result.setText("10.00");
        
        JLabel gpa = new JLabel();
        gpa.setFont(new Font ("Google Sans", 0, 18));
        gpa.setText("GPA");
        
        JButton add_course = new JButton();
        add_course.setFont(new Font("Google Sans Medium", 0, 12));
        add_course.setText("+ Add Course");
        add_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Courses (panel);
            }
        });
        
        JButton remove_course = new JButton();
        remove_course.setFont(new Font("Google Sans Medium", 0, 12));
        remove_course.setText("- Remove Course");
        remove_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_Courses (panel);
            }
        });
        
        if( initial_flag )
        {
           for(int i = 0; i<4; i++)
           {
               positionY_prevoius_coursename_textfield = (30*i);
               
               JTextField course_name = new JTextField();
               JTextField grade = new JTextField();
               JTextField credit = new JTextField();
               
               course_name.setFont(new java.awt.Font("Google Sans", 0, 12));
               grade.setFont(new java.awt.Font("Google Sans", 0, 12));
               credit.setFont(new java.awt.Font("Google Sans", 0, 12));
               
               course_name.setBorder(new EmptyBorder(0, 0, 0, 0));
               grade.setBorder(new EmptyBorder(0, 0, 0, 0));
               credit.setBorder(new EmptyBorder(0, 0, 0, 0));
               
               panel.add(course_name, new AbsoluteConstraints (10, 50 + (positionY_prevoius_coursename_textfield), 210, 30));
               panel.add(grade, new AbsoluteConstraints (220, 50 + (positionY_prevoius_coursename_textfield), 70, 30));
               panel.add(credit, new AbsoluteConstraints (290, 50 + (positionY_prevoius_coursename_textfield), 80, 30));         
               
               tf_course_name.add(course_name);
               tf_grade.add(grade);
               tf_credit.add(credit);
               
               ++textfield_counter;
               System.out.println("Y :"+ positionY_prevoius_coursename_textfield);
               
               revalidate();
               repaint();
           }
           initial_flag = false;
        }
        
        panel.add(head_title, new AbsoluteConstraints (10, 10, -1, -1));
        panel.add(result, new AbsoluteConstraints (440, 40, -1, -1));
        panel.add(gpa, new AbsoluteConstraints (500, 80, -1, -1));
        panel.add(add_course, new AbsoluteConstraints (440, 170, 110, 26));
        panel.add(remove_course, new AbsoluteConstraints (425, 143, -1, 26));
        
        scroll.setViewportView ( panel );
        scroll.getViewport().setScrollMode(JViewport.SIMPLE_SCROLL_MODE);
        
        // jPanel1.add( scroll,new AbsoluteConstraints (30, 120, 580, 220));
        jPanel1.add(panel);
        
        sp_semester_panel_scrollpane.add(scroll);
        panel_semester_panel.add(panel);
        label_semester_panel_title.add(head_title);
        label_result.add(result);
        button_add_course.add(add_course);
        button_remove_course.add(remove_course);
        
        ++semester_counter;
        
        panel.setVisible(true);
        scroll.setVisible(true);
        pack();
        revalidate();
        repaint();
     }
     private void Add_Courses (JPanel panel)
     {
        JTextField course_name = new JTextField();
        JTextField grade = new JTextField();
        JTextField credit = new JTextField();
               
        course_name.setFont(new java.awt.Font("Google Sans", 0, 12));
        grade.setFont(new java.awt.Font("Google Sans", 0, 12));
        credit.setFont(new java.awt.Font("Google Sans", 0, 12));
               
        course_name.setBorder(new EmptyBorder(0, 0, 0, 0));
        grade.setBorder(new EmptyBorder(0, 0, 0, 0));
        credit.setBorder(new EmptyBorder(0, 0, 0, 0));
        
        positionY_prevoius_coursename_textfield = positionY_prevoius_coursename_textfield + 30;
               
        panel.add(course_name, new AbsoluteConstraints (10, 50 + (positionY_prevoius_coursename_textfield), 210, 30));
        panel.add(grade, new AbsoluteConstraints (220, 50 + (positionY_prevoius_coursename_textfield), 70, 30));
        panel.add(credit, new AbsoluteConstraints (290, 50 + (positionY_prevoius_coursename_textfield), 80, 30));         
               
               tf_course_name.add(course_name);
               tf_grade.add(grade);
               tf_credit.add(credit);
               
               ++textfield_counter;
               System.out.println("Y :"+ positionY_prevoius_coursename_textfield);
               
               revalidate();
               repaint();
     }
     private void Remove_Courses (JPanel panel)
     {
         if(tf_course_name.size() > 1)
         {
            System.out.println("tf_course_name size :"+ tf_course_name.size());
            
            //(tf_course_name.get(tf_course_name.size() - 1)).setVisible(false);
            panel.remove((tf_course_name.get(tf_course_name.size() - 1)));
            tf_course_name.remove(tf_course_name.size() - 1);
            
            //(tf_grade.get(tf_grade.size() - 1)).setVisible(false);
            panel.remove(tf_grade.get(tf_grade.size() - 1));
            tf_grade.remove(tf_grade.size() - 1);
            
            //(tf_credit.get(tf_credit.size() - 1)).setVisible(false);
            panel.remove((tf_credit.get(tf_credit.size() - 1)));
            tf_credit.remove(tf_credit.size() - 1);
            
            positionY_prevoius_coursename_textfield = positionY_prevoius_coursename_textfield - 30;
            
            --textfield_counter;
         
            revalidate();
            repaint();
         }
     }
     private void Master()
     {
        recreate();
        //jPanel1.add((sp_semester_panel_scrollpane.get(sp_semester_panel_scrollpane.size() - 1)));
        //sp_semester_panel_scrollpane.get(0).setVisible(true);
        //jPanel1.add( sp_semester_panel_scrollpane.get(0),new AbsoluteConstraints (30, 120, 580, 220));
        this.revalidate();
        this.repaint();
        this.pack();
     }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Test_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Test_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Test_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Test_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Test_2().setVisible(true);
            }
        });
        
        GUI_Test_2 z = new GUI_Test_2 ();   
        z.Master();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
